In [1]:
# Dependencies and Setup
import pandas as pd
import datetime as dt

# File to Load 
load_accident_data = "data/US_Accidents_Dec20.csv"

# Read from CSV
accidents_df = pd.read_csv(load_accident_data)

accidents_df

,ID,Source,TMC,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1,MapQuest,201.0,3,2016-02-08 05:46:00,2016-02-08 11:00:00,39.865147,-84.058723,NaN,NaN,...,False,False,False,False,False,False,Night,Night,Night,Night
1,A-2,MapQuest,201.0,2,2016-02-08 06:07:59,2016-02-08 06:37:59,39.928059,-82.831184,NaN,NaN,...,False,False,False,False,False,False,Night,Night,Night,Day
2,A-3,MapQuest,201.0,2,2016-02-08 06:49:27,2016-02-08 07:19:27,39.063148,-84.032608,NaN,NaN,...,False,False,False,False,True,False,Night,Night,Day,Day
3,A-4,MapQuest,201.0,3,2016-02-08 07:23:34,2016-02-08 07:53:34,39.747753,-84.205582,NaN,NaN,...,False,False,False,False,False,False,Night,Day,Day,Day
4,A-5,MapQuest,201.0,2,2016-02-08 07:39:07,2016-02-08 08:09:07,39.627781,-84.188354,NaN,NaN,...,False,False,False,False,True,False,Day,Day,Day,Day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4232536,A-4239402,Bing,NaN,2,2019-08-23 18:03:25,2019-08-23 18:32:01,34.002480,-117.379360,33.99888,-117.37094,...,False,False,False,False,False,False,Day,Day,Day,Day
4232537,A-4239403,Bing,NaN,2,2019-08-23 19:11:30,2019-08-23 19:38:23,32.766960,-117.148060,32.76555,-117.15363,...,False,False,False,False,False,False,Day,Day,Day,Day
4232538,A-4239404,Bing,NaN,2,2019-08-23 19:00:21,2019-08-23 19:28:49,33.775450,-117.847790,33.77740,-117.85727,...,False,False,False,False,False,False,Day,Day,Day,Day
4232539,A-4239405,Bing,NaN,2,2019-08-23 19:00:21,2019-08-23 19:29:42,33.992460,-118.403020,33.98311,-118.39565,...,False,False,False,False,False,False,Day,Day,Day,Day
4232540,A-4239406,Bing,NaN,2,2019-08-23 18:52:06,2019-08-23 19:21:31,34.133930,-117.230920,34.13736,-117.23934,...,False,False,False,False,False,False,Day,Day,Day,Day

In [2]:
accidents_df["Source"].unique()

array(['MapQuest', 'MapQuest-Bing', 'Bing'], dtype=object)

In [3]:
accidents_df.dtypes

ID                        object
Source                    object
TMC                      float64
Severity                   int64
Start_Time                object
End_Time                  object
Start_Lat                float64
Start_Lng                float64
End_Lat                  float64
End_Lng                  float64
Distance(mi)             float64
Description               object
Number                   float64
Street                    object
Side                      object
City                      object
County                    object
State                     object
Zipcode                   object
Country                   object
Timezone                  object
Airport_Code              object
Weather_Timestamp         object
Temperature(F)           float64
Wind_Chill(F)            float64
Humidity(%)              float64
Pressure(in)             float64
Visibility(mi)           float64
Wind_Direction            object
Wind_Speed(mph)          float64
Precipitation(in)        float64
Weather_Condition         object
Amenity                     bool
Bump                        bool
Crossing                    bool
Give_Way                    bool
Junction                    bool
No_Exit                     bool
Railway                     bool
Roundabout                  bool
Station                     bool
Stop                        bool
Traffic_Calming             bool
Traffic_Signal              bool
Turning_Loop                bool
Sunrise_Sunset            object
Civil_Twilight            object
Nautical_Twilight         object
Astronomical_Twilight     object
dtype: object

In [2]:
#accidents_df = accidents_df["Start_Time"].astype('datetime64', copy=True)
accidents_df = accidents_df.astype({'Start_Time': 'datetime64'}) #.dtypes
accidents_df.dtypes

ID                               object
Source                           object
TMC                             float64
Severity                          int64
Start_Time               datetime64[ns]
End_Time                         object
Start_Lat                       float64
Start_Lng                       float64
End_Lat                         float64
End_Lng                         float64
Distance(mi)                    float64
Description                      object
Number                          float64
Street                           object
Side                             object
City                             object
County                           object
State                            object
Zipcode                          object
Country                          object
Timezone                         object
Airport_Code                     object
Weather_Timestamp                object
Temperature(F)                  float64
Wind_Chill(F)                   float64
Humidity(%)                     float64
Pressure(in)                    float64
Visibility(mi)                  float64
Wind_Direction                   object
Wind_Speed(mph)                 float64
Precipitation(in)               float64
Weather_Condition                object
Amenity                            bool
Bump                               bool
Crossing                           bool
Give_Way                           bool
Junction                           bool
No_Exit                            bool
Railway                            bool
Roundabout                         bool
Station                            bool
Stop                               bool
Traffic_Calming                    bool
Traffic_Signal                     bool
Turning_Loop                       bool
Sunrise_Sunset                   object
Civil_Twilight                   object
Nautical_Twilight                object
Astronomical_Twilight            object
dtype: object

In [3]:
most_recent = accidents_df.loc[(accidents_df["Start_Time"] >= pd.to_datetime('2018-01-01')) & (accidents_df["Start_Time"] < pd.to_datetime('2020-01-01'))]
#cutoff = pd.to_datetime('2019-01-01')
#cutoff
#df.sort_values(by=['col1'])
most_recent = most_recent.sort_values(by=['Start_Time'])
most_recent

,ID,Source,TMC,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
4081154,A-4088020,Bing,NaN,4,2018-01-01 00:07:06,2018-01-01 06:07:06,41.730490,-86.338150,41.704050,-86.625760,...,False,False,False,False,False,False,Night,Night,Night,Night
4081155,A-4088021,Bing,NaN,2,2018-01-01 00:08:27,2018-01-01 00:38:27,39.976279,-83.116542,39.976279,-83.116542,...,False,False,False,False,False,False,Night,Night,Night,Night
4081156,A-4088022,Bing,NaN,2,2018-01-01 00:08:27,2018-01-01 00:38:27,39.975830,-83.117170,39.975830,-83.117170,...,False,False,False,False,False,False,Night,Night,Night,Night
4081188,A-4088054,Bing,NaN,4,2018-01-01 00:13:51,2018-01-01 06:13:51,33.823210,-84.129240,33.824210,-84.150250,...,False,False,False,False,False,False,Night,Night,Night,Night
4081399,A-4088265,Bing,NaN,4,2018-01-01 00:14:30,2018-01-01 06:14:30,39.128510,-94.567830,39.130970,-94.567890,...,False,False,False,False,False,False,Night,Night,Night,Night
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
978772,A-978866,MapQuest,201.0,2,2019-12-31 23:56:42,2020-01-01 01:46:10,35.317268,-120.621109,NaN,NaN,...,False,False,False,False,False,False,Night,Night,Night,Night
3736039,A-3742900,Bing,NaN,3,2019-12-31 23:58:17,2020-01-01 00:27:03,41.901500,-87.920340,41.909630,-87.930190,...,False,False,False,False,False,False,Night,Night,Night,Night
3736038,A-3742899,Bing,NaN,3,2019-12-31 23:58:17,2020-01-01 00:27:03,41.875610,-87.641550,41.875710,-87.643550,...,False,False,False,False,False,False,Night,Night,Night,Night
3736037,A-3742898,Bing,NaN,3,2019-12-31 23:58:17,2020-01-01 00:27:03,41.872480,-87.645740,41.870360,-87.645080,...,False,False,False,False,False,False,Night,Night,Night,Night
3736040,A-3742901,Bing,NaN,3,2019-12-31 23:58:17,2020-01-01 00:27:03,41.874100,-87.645980,41.872480,-87.645740,...,False,False,False,False,False,False,Night,Night,Night,Night

In [6]:
most_recent.to_csv("data\most_recent.csv")

In [4]:
portland = most_recent.loc[most_recent["City"] == "Portland"]
portland

,ID,Source,TMC,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
2345760,A-2345879,MapQuest,201.0,3,2018-01-02 07:20:23,2018-01-02 08:04:31,45.541382,-122.477280,NaN,NaN,...,False,False,False,False,False,False,Night,Day,Day,Day
4082041,A-4088907,Bing,NaN,2,2018-01-02 07:28:51,2018-01-02 13:28:51,45.542299,-122.489044,45.54212,-122.502996,...,False,False,False,False,False,False,Night,Day,Day,Day
2345761,A-2345880,MapQuest,201.0,2,2018-01-02 07:40:05,2018-01-02 08:24:32,45.507286,-122.719719,NaN,NaN,...,False,False,False,False,False,False,Night,Day,Day,Day
2345762,A-2345881,MapQuest,201.0,2,2018-01-02 08:50:20,2018-01-02 09:35:05,45.447952,-122.598969,NaN,NaN,...,False,True,False,False,True,False,Day,Day,Day,Day
2345763,A-2345882,MapQuest,236.0,2,2018-01-02 09:45:56,2018-01-02 10:15:10,45.507233,-122.718979,NaN,NaN,...,False,False,False,False,False,False,Day,Day,Day,Day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3752694,A-3759555,Bing,NaN,2,2019-12-31 18:37:27,2019-12-31 22:37:27,45.415950,-122.744180,45.41595,-122.744180,...,False,False,False,False,False,False,Night,Night,Night,Night
990120,A-990214,MapQuest,201.0,2,2019-12-31 18:39:44,2019-12-31 19:09:20,45.504581,-122.486504,NaN,NaN,...,False,False,False,False,False,False,Night,Night,Night,Night
3752700,A-3759561,Bing,NaN,2,2019-12-31 19:04:26,2019-12-31 23:04:26,45.443620,-122.777440,45.44362,-122.777440,...,False,False,False,False,False,False,Night,Night,Night,Night
990121,A-990215,MapQuest,201.0,2,2019-12-31 20:35:48,2019-12-31 21:25:13,45.535069,-122.660629,NaN,NaN,...,False,False,False,False,True,False,Night,Night,Night,Night
3752711,A-3759572,Bing,NaN,2,2019-12-31 20:52:39,2020-01-01 00:52:39,45.556040,-122.678710,45.55604,-122.678710,...,False,False,False,False,False,False,Night,Night,Night,Night

In [38]:
weather = portland["Weather_Condition"].unique()
weather

array(['Clear', 'Mostly Cloudy', 'Overcast', 'Scattered Clouds',
       'Light Rain', 'Partly Cloudy', 'Rain', 'Light Snow', 'Shallow Fog',
       'Fog', 'Snow', 'Mist', 'Light Freezing Rain', 'Light Drizzle',
       'Light Thunderstorms and Rain', 'Thunderstorm', nan, 'Smoke',
       'Haze', 'Patches of Fog', 'Heavy Rain', 'Drizzle',
       'Light Freezing Fog', 'Light Freezing Drizzle', 'Cloudy', 'Fair',
       'Cloudy / Windy', 'Light Rain / Windy', 'Fair / Windy',
       'Thunder in the Vicinity', 'Thunder', 'Light Rain with Thunder',
       'Mostly Cloudy / Windy', 'Partly Cloudy / Windy', 'Snow and Sleet'],
      dtype=object)

In [39]:
desc = portland["Description"].unique()
desc

array(['Left lane blocked due to accident on I-84 Eastbound near Exit 13 181st Ave.',
       'At before 181st Ave/Exit 13 - Accident. Left lane blocked.',
       'Right hand shoulder blocked due to accident on US-26 Eastbound near Exit 72 Canyon Rd.',
       ..., 'Accident on I-5 Northbound at Exit 303 Going St.',
       'Accident on 171st Ave at Division St.',
       'Accident on OR-99E Grand Ave at Broadway.'], dtype=object)

In [40]:
amenity = portland["Amenity"].unique()
amenity

array([False,  True])

In [5]:
portland = portland[["Source", "Severity", "Start_Time", "Start_Lat", "Start_Lng", "City", "Zipcode", "Description", "Temperature(F)", "Weather_Condition", "Visibility(mi)", "Wind_Speed(mph)"]]
portland

,Source,Severity,Start_Time,Start_Lat,Start_Lng,City,Zipcode,Description,Temperature(F),Weather_Condition,Visibility(mi),Wind_Speed(mph)
2345760,MapQuest,3,2018-01-02 07:20:23,45.541382,-122.477280,Portland,97230,Left lane blocked due to accident on I-84 East...,37.9,Clear,10.0,20.7
4082041,Bing,2,2018-01-02 07:28:51,45.542299,-122.489044,Portland,97230,At before 181st Ave/Exit 13 - Accident. Left l...,37.9,Clear,10.0,20.7
2345761,MapQuest,2,2018-01-02 07:40:05,45.507286,-122.719719,Portland,97221,Right hand shoulder blocked due to accident on...,37.0,Mostly Cloudy,10.0,10.4
2345762,MapQuest,2,2018-01-02 08:50:20,45.447952,-122.598969,Portland,97222-2648,Accident on King Rd at Linwood Ave.,39.0,Mostly Cloudy,10.0,16.1
2345763,MapQuest,2,2018-01-02 09:45:56,45.507233,-122.718979,Portland,97221,Heavy traffic left lane closed and right hand ...,37.0,Mostly Cloudy,10.0,5.8
...,...,...,...,...,...,...,...,...,...,...,...,...
3752694,Bing,2,2019-12-31 18:37:27,45.415950,-122.744180,Portland,97223,At Carman Dr/Exit 291 - Accident.,49.0,Cloudy,10.0,18.0
990120,MapQuest,2,2019-12-31 18:39:44,45.504581,-122.486504,Portland,97236-1241,Accident on 171st Ave at Division St.,51.0,Light Rain,10.0,17.0
3752700,Bing,2,2019-12-31 19:04:26,45.443620,-122.777440,Portland,97223,At Greenburg Rd/Exit 5 - Accident.,49.0,Cloudy,10.0,18.0
990121,MapQuest,2,2019-12-31 20:35:48,45.535069,-122.660629,Portland,97232-1153,Accident on OR-99E Grand Ave at Broadway.,50.0,Light Rain,10.0,13.0
3752711,Bing,2,2019-12-31 20:52:39,45.556040,-122.678710,Portland,97217,At Killingsworth St/Exit 303 - Accident.,50.0,Light Rain,7.0,6.0

In [6]:
portland_na = portland.dropna()
portland_na

,Source,Severity,Start_Time,Start_Lat,Start_Lng,City,Zipcode,Description,Temperature(F),Weather_Condition,Visibility(mi),Wind_Speed(mph)
2345760,MapQuest,3,2018-01-02 07:20:23,45.541382,-122.477280,Portland,97230,Left lane blocked due to accident on I-84 East...,37.9,Clear,10.0,20.7
4082041,Bing,2,2018-01-02 07:28:51,45.542299,-122.489044,Portland,97230,At before 181st Ave/Exit 13 - Accident. Left l...,37.9,Clear,10.0,20.7
2345761,MapQuest,2,2018-01-02 07:40:05,45.507286,-122.719719,Portland,97221,Right hand shoulder blocked due to accident on...,37.0,Mostly Cloudy,10.0,10.4
2345762,MapQuest,2,2018-01-02 08:50:20,45.447952,-122.598969,Portland,97222-2648,Accident on King Rd at Linwood Ave.,39.0,Mostly Cloudy,10.0,16.1
2345763,MapQuest,2,2018-01-02 09:45:56,45.507233,-122.718979,Portland,97221,Heavy traffic left lane closed and right hand ...,37.0,Mostly Cloudy,10.0,5.8
...,...,...,...,...,...,...,...,...,...,...,...,...
3752694,Bing,2,2019-12-31 18:37:27,45.415950,-122.744180,Portland,97223,At Carman Dr/Exit 291 - Accident.,49.0,Cloudy,10.0,18.0
990120,MapQuest,2,2019-12-31 18:39:44,45.504581,-122.486504,Portland,97236-1241,Accident on 171st Ave at Division St.,51.0,Light Rain,10.0,17.0
3752700,Bing,2,2019-12-31 19:04:26,45.443620,-122.777440,Portland,97223,At Greenburg Rd/Exit 5 - Accident.,49.0,Cloudy,10.0,18.0
990121,MapQuest,2,2019-12-31 20:35:48,45.535069,-122.660629,Portland,97232-1153,Accident on OR-99E Grand Ave at Broadway.,50.0,Light Rain,10.0,13.0
3752711,Bing,2,2019-12-31 20:52:39,45.556040,-122.678710,Portland,97217,At Killingsworth St/Exit 303 - Accident.,50.0,Light Rain,7.0,6.0

In [18]:
#portland_na.to_csv("data\portland_cleaned.csv", index_label="ID")
portland_na.to_json("data\portland_cleaned.json", orient="records")

In [7]:
portland_json = portland_na

#for index, row in portland_json.iterrows():
portland_json.insert(loc=0,column="Accident", value="Accident", allow_duplicates=True)

portland_json.to_csv("data\portland_cleaned.csv", index=False)

In [ ]:

for index, row in portland_json.iterrows():
    portland_json[index,"Object"] = "Accident"

portland_json

C:\Users\mrpar\.conda\envs\PythonData\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [16]:
import csv
import json

csvfile = open('data\portland_cleaned.csv', 'r')
jsonfile = open('data\portland_cleaned.json', 'w')

#fieldnames = ("Source", "Severity", "Start_Time", "Start_Lat", "Start_Lng", "City", "Zipcode", "Description", "Temperature(F)", "Weather_Condition", "Visibility(mi)", "Wind_Speed(mph)")
reader = csv.DictReader(csvfile)
for row in reader:
    jsonfile.write('[{accident: {')
    json.dump(row, jsonfile)
    jsonfile.write('}]\n')

In [14]:
import csv
import json

csvFilePath = 'data\portland_cleaned.csv'
jsonFilePath = 'data\portland_cleaned.json'

data = {}
with open(csvFilePath) as csvFile:
    csvReader = csv.DictReader(csvFile)
    for rows in csvReader:
        id = rows['ID']
        data[id] = rows

with open(jsonFilePath, 'w') as jsonFile:
    jsonFile.write(json.dumps(data, indent = 4))