In [2]:
# Dependencies and Setup
import pandas as pd
import datetime as dt

# File to Load 
load_accident_data = "data/US_Accidents_Dec20.csv"

# Read from CSV
accidents_df = pd.read_csv(load_accident_data)

accidents_df

,ID,Source,TMC,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1,MapQuest,201.0,3,2016-02-08 05:46:00,2016-02-08 11:00:00,39.865147,-84.058723,NaN,NaN,...,False,False,False,False,False,False,Night,Night,Night,Night
1,A-2,MapQuest,201.0,2,2016-02-08 06:07:59,2016-02-08 06:37:59,39.928059,-82.831184,NaN,NaN,...,False,False,False,False,False,False,Night,Night,Night,Day
2,A-3,MapQuest,201.0,2,2016-02-08 06:49:27,2016-02-08 07:19:27,39.063148,-84.032608,NaN,NaN,...,False,False,False,False,True,False,Night,Night,Day,Day
3,A-4,MapQuest,201.0,3,2016-02-08 07:23:34,2016-02-08 07:53:34,39.747753,-84.205582,NaN,NaN,...,False,False,False,False,False,False,Night,Day,Day,Day
4,A-5,MapQuest,201.0,2,2016-02-08 07:39:07,2016-02-08 08:09:07,39.627781,-84.188354,NaN,NaN,...,False,False,False,False,True,False,Day,Day,Day,Day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4232536,A-4239402,Bing,NaN,2,2019-08-23 18:03:25,2019-08-23 18:32:01,34.002480,-117.379360,33.99888,-117.37094,...,False,False,False,False,False,False,Day,Day,Day,Day
4232537,A-4239403,Bing,NaN,2,2019-08-23 19:11:30,2019-08-23 19:38:23,32.766960,-117.148060,32.76555,-117.15363,...,False,False,False,False,False,False,Day,Day,Day,Day
4232538,A-4239404,Bing,NaN,2,2019-08-23 19:00:21,2019-08-23 19:28:49,33.775450,-117.847790,33.77740,-117.85727,...,False,False,False,False,False,False,Day,Day,Day,Day
4232539,A-4239405,Bing,NaN,2,2019-08-23 19:00:21,2019-08-23 19:29:42,33.992460,-118.403020,33.98311,-118.39565,...,False,False,False,False,False,False,Day,Day,Day,Day
4232540,A-4239406,Bing,NaN,2,2019-08-23 18:52:06,2019-08-23 19:21:31,34.133930,-117.230920,34.13736,-117.23934,...,False,False,False,False,False,False,Day,Day,Day,Day

In [3]:
accidents_df["Source"].unique()

array(['MapQuest', 'MapQuest-Bing', 'Bing'], dtype=object)

In [4]:
accidents_df.dtypes

ID                        object
Source                    object
TMC                      float64
Severity                   int64
Start_Time                object
End_Time                  object
Start_Lat                float64
Start_Lng                float64
End_Lat                  float64
End_Lng                  float64
Distance(mi)             float64
Description               object
Number                   float64
Street                    object
Side                      object
City                      object
County                    object
State                     object
Zipcode                   object
Country                   object
Timezone                  object
Airport_Code              object
Weather_Timestamp         object
Temperature(F)           float64
Wind_Chill(F)            float64
Humidity(%)              float64
Pressure(in)             float64
Visibility(mi)           float64
Wind_Direction            object
Wind_Speed(mph)          float64
Precipitation(in)        float64
Weather_Condition         object
Amenity                     bool
Bump                        bool
Crossing                    bool
Give_Way                    bool
Junction                    bool
No_Exit                     bool
Railway                     bool
Roundabout                  bool
Station                     bool
Stop                        bool
Traffic_Calming             bool
Traffic_Signal              bool
Turning_Loop                bool
Sunrise_Sunset            object
Civil_Twilight            object
Nautical_Twilight         object
Astronomical_Twilight     object
dtype: object

In [5]:
#accidents_df = accidents_df["Start_Time"].astype('datetime64', copy=True)
accidents_df = accidents_df.astype({'Start_Time': 'datetime64'}) #.dtypes
accidents_df.dtypes

ID                               object
Source                           object
TMC                             float64
Severity                          int64
Start_Time               datetime64[ns]
End_Time                         object
Start_Lat                       float64
Start_Lng                       float64
End_Lat                         float64
End_Lng                         float64
Distance(mi)                    float64
Description                      object
Number                          float64
Street                           object
Side                             object
City                             object
County                           object
State                            object
Zipcode                          object
Country                          object
Timezone                         object
Airport_Code                     object
Weather_Timestamp                object
Temperature(F)                  float64
Wind_Chill(F)                   float64
Humidity(%)                     float64
Pressure(in)                    float64
Visibility(mi)                  float64
Wind_Direction                   object
Wind_Speed(mph)                 float64
Precipitation(in)               float64
Weather_Condition                object
Amenity                            bool
Bump                               bool
Crossing                           bool
Give_Way                           bool
Junction                           bool
No_Exit                            bool
Railway                            bool
Roundabout                         bool
Station                            bool
Stop                               bool
Traffic_Calming                    bool
Traffic_Signal                     bool
Turning_Loop                       bool
Sunrise_Sunset                   object
Civil_Twilight                   object
Nautical_Twilight                object
Astronomical_Twilight            object
dtype: object

In [9]:
most_recent = accidents_df.loc[accidents_df["Start_Time"] >= pd.to_datetime('2019-01-01')]
#cutoff = pd.to_datetime('2019-01-01')
#cutoff
#df.sort_values(by=['col1'])
most_recent = most_recent.sort_values(by=['Start_Time'])
most_recent

,ID,Source,TMC,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
3911749,A-3918613,Bing,NaN,4,2019-01-01 00:00:00,2019-01-01 06:00:00,40.829567,-81.366130,40.829571,-81.366117,...,False,False,False,False,False,False,Night,Night,Night,Night
3911747,A-3918611,Bing,NaN,4,2019-01-01 00:00:00,2019-01-01 06:00:00,40.830360,-81.363980,40.829768,-81.366126,...,False,False,False,False,False,False,Night,Night,Night,Night
3911745,A-3918609,Bing,NaN,4,2019-01-01 00:00:00,2019-01-01 06:00:00,40.828231,-81.366190,40.829770,-81.366120,...,False,False,False,False,False,False,Night,Night,Night,Night
1615988,A-1616096,MapQuest,201.0,3,2019-01-01 00:00:50,2019-01-01 00:30:38,37.742043,-121.566734,NaN,NaN,...,False,False,False,False,False,False,Night,Night,Night,Night
1615989,A-1616097,MapQuest,201.0,3,2019-01-01 00:03:14,2019-01-01 00:33:05,37.742203,-121.531143,NaN,NaN,...,False,False,False,False,False,False,Night,Night,Night,Night
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
513368,A-513386,MapQuest,241.0,2,2020-12-31 22:50:29,2020-12-31 23:19:51,40.522301,-111.938889,NaN,NaN,...,False,False,False,False,True,False,Night,Night,Night,Night
3041801,A-3043223,Bing,NaN,2,2020-12-31 22:51:32,2020-12-31 23:51:32,44.093917,-123.104027,44.096457,-123.108917,...,False,False,False,False,False,False,Night,Night,Night,Night
3405596,A-3412011,Bing,NaN,2,2020-12-31 22:51:32,2020-12-31 23:51:32,44.093917,-123.104027,44.096457,-123.108917,...,False,False,False,False,False,False,Night,Night,Night,Night
512936,A-512953,MapQuest,241.0,3,2020-12-31 22:57:02,2020-12-31 23:58:36,41.932789,-88.038078,NaN,NaN,...,False,False,False,False,False,False,Night,Night,Night,Night
3246425,A-3250725,Bing,NaN,2,2020-12-31 23:28:56,2020-12-31 23:59:37,45.024064,-123.827623,45.049374,-123.785633,...,False,False,False,False,False,False,Night,Night,Night,Night

In [10]:
most_recent.to_csv("data\most_recent.csv")

In [11]:
portland = most_recent.loc[most_recent["City"] == "Portland"]
portland

,ID,Source,TMC,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
1615955,A-1616063,MapQuest-Bing,201.0,3,2019-01-01 00:48:25,2019-01-01 01:18:09,45.501747,-122.565361,NaN,NaN,...,False,False,False,False,False,False,Night,Night,Night,Night
3912023,A-3918887,Bing,NaN,2,2019-01-01 01:52:42,2019-01-01 05:52:42,45.533847,-122.580483,45.533340,-122.579050,...,False,False,False,False,False,False,Night,Night,Night,Night
1615959,A-1616067,MapQuest,201.0,3,2019-01-01 02:38:51,2019-01-01 03:08:12,45.534191,-122.579781,NaN,NaN,...,False,False,False,False,False,False,Night,Night,Night,Night
1615334,A-1615442,MapQuest,241.0,3,2019-01-01 03:26:56,2019-01-01 03:55:48,42.859890,-84.885353,NaN,NaN,...,False,False,False,False,False,False,Night,Night,Night,Night
3912035,A-3918899,Bing,NaN,2,2019-01-01 03:33:49,2019-01-01 07:33:49,45.570512,-122.550697,45.570507,-122.550703,...,False,False,False,False,False,False,Night,Night,Night,Night
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2976194,A-2976648,Bing,NaN,2,2020-12-31 19:51:37,2020-12-31 20:51:37,45.507939,-122.669176,45.507009,-122.670770,...,False,False,False,False,False,False,Night,Night,Night,Night
3385656,A-3391796,Bing,NaN,2,2020-12-31 20:09:26,2020-12-31 20:25:07,45.505141,-122.673546,45.511584,-122.667153,...,False,False,False,False,True,False,Night,Night,Night,Night
3287412,A-3292282,Bing,NaN,2,2020-12-31 20:09:26,2020-12-31 20:25:07.000000000,45.505141,-122.673546,45.511584,-122.667153,...,False,False,False,False,True,False,Night,Night,Night,Night
2954034,A-2954167,Bing,NaN,2,2020-12-31 20:09:31,2020-12-31 22:09:31,45.466629,-122.693606,45.463319,-122.699676,...,False,False,False,False,False,False,Night,Night,Night,Night
3305863,A-3311027,Bing,NaN,2,2020-12-31 20:09:31,2020-12-31 22:09:31,45.466629,-122.693606,45.463319,-122.699676,...,False,False,False,False,False,False,Night,Night,Night,Night