In [1]:
import numpy as np
import pandas as pd
import requests
from census import Census

# Census API Key

from config import api_key
c = Census(api_key, year=2016)

In [2]:
# Run Census Search to retrieve data on all zip codes (2018 ACS5 Census)
# See: https://github.com/datamade/census for library documentation
# See: https://gist.github.com/afhaque/60558290d6efd892351c4b64e5c01e9b for labels
# Code sourced from Oregon Data Bootcamp Class Activities 6.3.8
census_data = c.acs5.get(("NAME", "B19013_001E", "B01003_001E", "B01002_001E", "B19301_001E", "B17001_002E"), {'for': 'zip code tabulation area:*'})

# Convert to DataFrame
census_pd = pd.DataFrame(census_data)

# Column Reordering
census_pd = census_pd.rename(columns={"B01003_001E": "Population",
                                      "B01002_001E": "Median Age",
                                      "B19013_001E": "Household Income",
                                      "B19301_001E": "Per Capita Income",
                                      "B17001_002E": "Poverty Count",
                                      "NAME": "Name", "zip code tabulation area": "Zipcode"})

# Organize Columns
census_2016 = census_pd[["Zipcode", "Population", "Median Age", "Household Income", "Per Capita Income", 
                         "Poverty Count"]]

census_2016.head()

,Zipcode,Population,Median Age,Household Income,Per Capita Income,Poverty Count
0,05762,513.0,39.2,58558.0,24235.0,50.0
1,05763,2715.0,43.9,54968.0,29674.0,488.0
2,05764,3370.0,41.3,44468.0,22651.0,323.0
3,05765,1632.0,46.7,56771.0,30786.0,85.0
4,05766,598.0,45.9,52250.0,33227.0,76.0

In [3]:
# Keep only PDX zipcodes
# Zipcodes chosen based on information from City of Portland (https://www.portlandoregon.gov/revenue/article/373203)
census_2016_pdx = census_2016.loc[census_2016['Zipcode'].isin(['97201', '97202', '97203', '97204', '97205', '97206',
                                                               '97209', '97210', '97211', '97212', '97213', '97214', 
                                                               '97215', '97216', '97217', '97218', '97219', '97220', 
                                                               '97221', '97222', '97223', '97225', '97227', '97229',
                                                               '97230', '97231', '97232', '97233', '97236', '97239', 
                                                               '97258', '97266'])]

print(census_2016_pdx)

      Zipcode  Population  Median Age  Household Income  Per Capita Income  \
26831   97201     16946.0        30.9           45885.0            46243.0
26832   97202     41719.0        35.4           61768.0            38280.0
26833   97203     33715.0        32.8           51056.0            23515.0
26834   97204      1033.0        43.7           15833.0            16859.0
26835   97205      7262.0        41.6           32553.0            41630.0
26836   97206     49935.0        37.7           55887.0            27818.0
26838   97209     15578.0        38.0           52726.0            57260.0
26839   97210     11371.0        37.9           80352.0            77318.0
26840   97211     34303.0        35.7           71671.0            33753.0
26841   97212     26256.0        39.7           90310.0            49797.0
26842   97213     31889.0        39.2           64186.0            36042.0
26843   97214     25024.0        34.6           57053.0            39129.0
26844   97215     17499.0        40.5           72570.0            44575.0
26845   97216     16863.0        37.9           41896.0            21670.0
26846   97217     32371.0        37.1           61830.0            33726.0
26847   97218     15454.0        35.7           56056.0            24748.0
26848   97219     40946.0        39.0           84566.0            46119.0
26849   97220     29810.0        37.2           46392.0            23633.0
26850   97221     12615.0        43.6          102414.0            58203.0
26851   97222     35866.0        39.5           52340.0            26916.0
26852   97223     49348.0        37.7           68541.0            34755.0
26854   97225     25519.0        41.6           74402.0            47400.0
26855   97227      4433.0        33.4           49154.0            35127.0
26856   97229     63867.0        38.1          102035.0            49097.0
26857   97230     40433.0        37.9           46721.0            24792.0
26858   97231      3655.0        52.7           93583.0            70347.0
26859   97232     12545.0        35.8           54483.0            42777.0
26860   97233     41697.0        31.7           40160.0            16816.0
26861   97236     39237.0        35.2           41976.0            20393.0
26862   97239     16190.0        39.5           82306.0            58433.0
26863   97266     35299.0        35.1           40904.0            18822.0

       Poverty Count
26831         3711.0
26832         6007.0
26833         8253.0
26834          329.0
26835         1881.0
26836         6761.0
26838         3014.0
26839          846.0
26840         4431.0
26841         2378.0
26842         3647.0
26843         3539.0
26844         1133.0
26845         4200.0
26846         4853.0
26847         4393.0
26848         3593.0
26849         5158.0
26850          701.0
26851         5203.0
26852         5254.0
26854         1438.0
26855          884.0
26856         3475.0
26857         8176.0
26858          190.0
26859         1798.0
26860        11751.0
26861        10658.0
26862         1816.0
26863         8565.0

In [4]:
# Calculate Poverty Rate
census_2016_pdx["Poverty Rate"] = 100 * \
    census_2016_pdx["Poverty Count"].astype(
        int) / census_pd["Population"].astype(int)

# Add the column to the dataframe
census_2016_pdx = census_2016_pdx[["Zipcode", "Population", "Median Age", "Household Income", "Per Capita Income", 
                         "Poverty Count", "Poverty Rate"]]

census_2016_pdx.head()

C:\Users\rylee.ahnen\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

,Zipcode,Population,Median Age,Household Income,Per Capita Income,Poverty Count,Poverty Rate
26831,97201,16946.0,30.9,45885.0,46243.0,3711.0,21.898973
26832,97202,41719.0,35.4,61768.0,38280.0,6007.0,14.398715
26833,97203,33715.0,32.8,51056.0,23515.0,8253.0,24.478719
26834,97204,1033.0,43.7,15833.0,16859.0,329.0,31.848984
26835,97205,7262.0,41.6,32553.0,41630.0,1881.0,25.901955

In [5]:
# Export file to json
census_2016_pdx.to_json("cleaned_census\census_2016_pdx.json", orient="records")