In [1]:
import numpy as np
import pandas as pd

In [2]:
# Read in the separate data files

census_2016 = pd.read_json("cleaned_census\census_2016_pdx.json")
census_2017 = pd.read_json("cleaned_census\census_2017_pdx.json")
census_2018 = pd.read_json("cleaned_census\census_2018_pdx.json")
census_2019 = pd.read_json("cleaned_census\census_2019_pdx.json")

In [3]:
frames = [census_2016, census_2017, census_2018, census_2019]
census_merged = pd.concat(frames)

In [4]:
census_merged.head(50)

,Zipcode,Population,Median Age,Household Income,Per Capita Income,Poverty Count,Poverty Rate,Year
0,97201,16946,30.9,45885,46243,3711,21.898973,2016
1,97202,41719,35.4,61768,38280,6007,14.398715,2016
2,97203,33715,32.8,51056,23515,8253,24.478719,2016
3,97204,1033,43.7,15833,16859,329,31.848984,2016
4,97205,7262,41.6,32553,41630,1881,25.901955,2016
5,97206,49935,37.7,55887,27818,6761,13.539601,2016
6,97209,15578,38.0,52726,57260,3014,19.347798,2016
7,97210,11371,37.9,80352,77318,846,7.439979,2016
8,97211,34303,35.7,71671,33753,4431,12.917238,2016
9,97212,26256,39.7,90310,49797,2378,9.056977,2016
10,97213,31889,39.2,64186,36042,3647,11.436546,2016
11,97214,25024,34.6,57053,39129,3539,14.142423,2016
12,97215,17499,40.5,72570,44575,1133,6.474656,2016
13,97216,16863,37.9,41896,21670,4200,24.906600,2016
14,97217,32371,37.1,61830,33726,4853,14.991814,2016
15,97218,15454,35.7,56056,24748,4393,28.426297,2016
16,97219,40946,39.0,84566,46119,3593,8.774972,2016
17,97220,29810,37.2,46392,23633,5158,17.302918,2016
18,97221,12615,43.6,102414,58203,701,5.556877,2016
19,97222,35866,39.5,52340,26916,5203,14.506775,2016
20,97223,49348,37.7,68541,34755,5254,10.646835,2016
21,97225,25519,41.6,74402,47400,1438,5.635017,2016
22,97227,4433,33.4,49154,35127,884,19.941349,2016
23,97229,63867,38.1,102035,49097,3475,5.440995,2016
24,97230,40433,37.9,46721,24792,8176,20.221107,2016
25,97231,3655,52.7,93583,70347,190,5.198358,2016
26,97232,12545,35.8,54483,42777,1798,14.332403,2016
27,97233,41697,31.7,40160,16816,11751,28.181884,2016
28,97236,39237,35.2,41976,20393,10658,27.163137,2016
29,97239,16190,39.5,82306,58433,1816,11.216800,2016
30,97266,35299,35.1,40904,18822,8565,24.264143,2016
0,97201,17566,31.6,50420,48517,4018,22.873733,2017
1,97202,42189,35.8,66017,40809,5635,13.356562,2017
2,97203,34089,32.4,55174,25359,7877,23.107161,2017
3,97204,1053,43.7,-666666666,17887,345,32.763533,2017
4,97205,7122,42.9,32276,42623,2064,28.980623,2017
5,97206,50655,37.4,59622,29550,6764,13.353075,2017
6,97209,16507,38.9,54747,57442,3047,18.458836,2017
7,97210,11676,36.1,88947,75997,762,6.526208,2017
8,97211,34856,35.8,73312,36065,4339,12.448359,2017
9,97212,26601,39.5,94192,52153,2325,8.740273,2017
10,97213,32284,39.6,67882,38435,3170,9.819105,2017
11,97214,25398,34.8,60754,41420,3541,13.942043,2017
12,97215,17939,40.3,76178,45599,1394,7.770779,2017
13,97216,17112,37.6,41809,21755,3797,22.189107,2017
14,97217,34327,37.0,70027,36762,4774,13.907420,2017
15,97218,15556,35.2,58853,25762,4231,27.198509,2017
16,97219,41534,38.8,89745,48734,3520,8.474984,2017
17,97220,30374,37.4,47284,24249,5228,17.212089,2017
18,97221,12363,44.5,98919,62307,723,5.848095,2017

In [7]:
census_merged.rename(columns={
    'Median Age': "MedianAge",
    'Household Income': "HouseholdIncome",
    'Per Capita Income': "PerCapitaIncome",
    'Poverty Count': "PovertyCount",
    'Poverty Rate': "PovertyRate"
}, inplace=True)
census_merged

,Zipcode,Population,MedianAge,HouseholdIncome,PerCapitaIncome,PovertyCount,PovertyRate,Year
0,97201,16946,30.9,45885,46243,3711,21.898973,2016
1,97202,41719,35.4,61768,38280,6007,14.398715,2016
2,97203,33715,32.8,51056,23515,8253,24.478719,2016
3,97204,1033,43.7,15833,16859,329,31.848984,2016
4,97205,7262,41.6,32553,41630,1881,25.901955,2016
...,...,...,...,...,...,...,...,...
26,97232,13706,35.9,63059,50222,1477,10.776302,2019
27,97233,40477,32.6,42452,19983,10328,25.515725,2019
28,97236,40892,35.4,50663,22894,8710,21.300010,2019
29,97239,18190,39.5,93459,64854,1673,9.197361,2019
30,97266,35727,36.9,53984,25189,7103,19.881322,2019

In [8]:
# Export file to json
census_merged.to_json("cleaned_census\census_merged.json", orient="records")