In [1]:
# Dependencies and Setup
import pandas as pd
import datetime as dt

# File to Load 
load_accident_data = "data/US_Accidents_Dec20.csv"

# Read from CSV
accidents_df = pd.read_csv(load_accident_data)

accidents_df

,ID,Source,TMC,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1,MapQuest,201.0,3,2016-02-08 05:46:00,2016-02-08 11:00:00,39.865147,-84.058723,NaN,NaN,...,False,False,False,False,False,False,Night,Night,Night,Night
1,A-2,MapQuest,201.0,2,2016-02-08 06:07:59,2016-02-08 06:37:59,39.928059,-82.831184,NaN,NaN,...,False,False,False,False,False,False,Night,Night,Night,Day
2,A-3,MapQuest,201.0,2,2016-02-08 06:49:27,2016-02-08 07:19:27,39.063148,-84.032608,NaN,NaN,...,False,False,False,False,True,False,Night,Night,Day,Day
3,A-4,MapQuest,201.0,3,2016-02-08 07:23:34,2016-02-08 07:53:34,39.747753,-84.205582,NaN,NaN,...,False,False,False,False,False,False,Night,Day,Day,Day
4,A-5,MapQuest,201.0,2,2016-02-08 07:39:07,2016-02-08 08:09:07,39.627781,-84.188354,NaN,NaN,...,False,False,False,False,True,False,Day,Day,Day,Day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4232536,A-4239402,Bing,NaN,2,2019-08-23 18:03:25,2019-08-23 18:32:01,34.002480,-117.379360,33.99888,-117.37094,...,False,False,False,False,False,False,Day,Day,Day,Day
4232537,A-4239403,Bing,NaN,2,2019-08-23 19:11:30,2019-08-23 19:38:23,32.766960,-117.148060,32.76555,-117.15363,...,False,False,False,False,False,False,Day,Day,Day,Day
4232538,A-4239404,Bing,NaN,2,2019-08-23 19:00:21,2019-08-23 19:28:49,33.775450,-117.847790,33.77740,-117.85727,...,False,False,False,False,False,False,Day,Day,Day,Day
4232539,A-4239405,Bing,NaN,2,2019-08-23 19:00:21,2019-08-23 19:29:42,33.992460,-118.403020,33.98311,-118.39565,...,False,False,False,False,False,False,Day,Day,Day,Day
4232540,A-4239406,Bing,NaN,2,2019-08-23 18:52:06,2019-08-23 19:21:31,34.133930,-117.230920,34.13736,-117.23934,...,False,False,False,False,False,False,Day,Day,Day,Day

In [2]:
accidents_df["Weather_Condition"].unique()

array(['Light Rain', 'Overcast', 'Mostly Cloudy', 'Rain', 'Light Snow',
       'Haze', 'Scattered Clouds', 'Partly Cloudy', 'Clear', 'Snow',
       'Light Freezing Drizzle', 'Light Drizzle', 'Fog', 'Shallow Fog',
       'Heavy Rain', 'Light Freezing Rain', 'Cloudy', 'Drizzle', nan,
       'Light Rain Showers', 'Mist', 'Smoke', 'Patches of Fog',
       'Light Freezing Fog', 'Light Haze', 'Light Thunderstorms and Rain',
       'Thunderstorms and Rain', 'Fair', 'Volcanic Ash', 'Blowing Sand',
       'Blowing Dust / Windy', 'Widespread Dust', 'Fair / Windy',
       'Rain Showers', 'Mostly Cloudy / Windy', 'Light Rain / Windy',
       'Hail', 'Heavy Drizzle', 'Showers in the Vicinity', 'Thunderstorm',
       'Light Rain Shower', 'Light Rain with Thunder',
       'Partly Cloudy / Windy', 'Thunder in the Vicinity', 'T-Storm',
       'Heavy Thunderstorms and Rain', 'Thunder', 'Heavy T-Storm',
       'Funnel Cloud', 'Heavy T-Storm / Windy', 'Blowing Snow',
       'Light Thunderstorms and Snow', 'Heavy Snow', 'Low Drifting Snow',
       'Light Ice Pellets', 'Ice Pellets', 'Squalls', 'N/A Precipitation',
       'Cloudy / Windy', 'Light Fog', 'Sand', 'Snow Grains',
       'Snow Showers', 'Heavy Thunderstorms and Snow', 'Rain / Windy',
       'Heavy Rain / Windy', 'Heavy Ice Pellets', 'Light Snow / Windy',
       'Heavy Freezing Rain', 'Small Hail', 'Heavy Rain Showers',
       'Wintry Mix', 'Drizzle and Fog', 'Wintry Mix / Windy',
       'Snow / Windy', 'Heavy Snow / Windy', 'T-Storm / Windy',
       'Fog / Windy', 'Haze / Windy', 'Snow and Sleet / Windy',
       'Blowing Snow / Windy', 'Light Snow and Sleet', 'Light Sleet',
       'Thunder / Windy', 'Rain Shower', 'Light Drizzle / Windy',
       'Partial Fog', 'Squalls / Windy', 'Smoke / Windy',
       'Sand / Dust Whirlwinds', 'Blowing Dust',
       'Light Snow with Thunder', 'Thunder / Wintry Mix',
       'Thunder / Wintry Mix / Windy', 'Light Rain Shower / Windy',
       'Patches of Fog / Windy', 'Drizzle / Windy', 'Snow and Sleet',
       'Light Freezing Rain / Windy', 'Light Snow Shower',
       'Light Snow and Sleet / Windy', 'Freezing Rain',
       'Freezing Drizzle', 'Sleet', 'Rain and Sleet', 'Heavy Sleet',
       'Light Snow Grains', 'Partial Fog / Windy',
       'Widespread Dust / Windy', 'Sand / Dust Whirlwinds / Windy',
       'Tornado', 'Snow and Thunder', 'Heavy Snow with Thunder',
       'Light Snow Showers', 'Heavy Blowing Snow', 'Light Hail',
       'Heavy Smoke', 'Heavy Thunderstorms with Small Hail',
       'Light Thunderstorm', 'Heavy Freezing Drizzle',
       'Light Blowing Snow', 'Thunderstorms and Snow',
       'Freezing Rain / Windy', 'Dust Whirls', 'Light Sleet / Windy',
       'Mist / Windy', 'Sleet / Windy', 'Sand / Dust Whirls Nearby',
       'Heavy Rain Shower', 'Thunder and Hail', 'Drifting Snow',
       'Thunder and Hail / Windy'], dtype=object)

In [3]:
accidents_df.dtypes

ID                        object
Source                    object
TMC                      float64
Severity                   int64
Start_Time                object
End_Time                  object
Start_Lat                float64
Start_Lng                float64
End_Lat                  float64
End_Lng                  float64
Distance(mi)             float64
Description               object
Number                   float64
Street                    object
Side                      object
City                      object
County                    object
State                     object
Zipcode                   object
Country                   object
Timezone                  object
Airport_Code              object
Weather_Timestamp         object
Temperature(F)           float64
Wind_Chill(F)            float64
Humidity(%)              float64
Pressure(in)             float64
Visibility(mi)           float64
Wind_Direction            object
Wind_Speed(mph)          float64
Precipitation(in)        float64
Weather_Condition         object
Amenity                     bool
Bump                        bool
Crossing                    bool
Give_Way                    bool
Junction                    bool
No_Exit                     bool
Railway                     bool
Roundabout                  bool
Station                     bool
Stop                        bool
Traffic_Calming             bool
Traffic_Signal              bool
Turning_Loop                bool
Sunrise_Sunset            object
Civil_Twilight            object
Nautical_Twilight         object
Astronomical_Twilight     object
dtype: object

In [5]:
# Caste Start_Time into datetime data type
accidents_df["Start_Time_caste"] = accidents_df["Start_Time"]
accidents_df = accidents_df.astype({'Start_Time_caste': 'datetime64'}) 
#accidents_df = accidents_df['Zipcode'].loc[accidents_df['Zipcode'].str[:5]]
accidents_df.dtypes

ID                               object
Source                           object
TMC                             float64
Severity                          int64
Start_Time                       object
End_Time                         object
Start_Lat                       float64
Start_Lng                       float64
End_Lat                         float64
End_Lng                         float64
Distance(mi)                    float64
Description                      object
Number                          float64
Street                           object
Side                             object
City                             object
County                           object
State                            object
Zipcode                          object
Country                          object
Timezone                         object
Airport_Code                     object
Weather_Timestamp                object
Temperature(F)                  float64
Wind_Chill(F)                   float64
Humidity(%)                     float64
Pressure(in)                    float64
Visibility(mi)                  float64
Wind_Direction                   object
Wind_Speed(mph)                 float64
Precipitation(in)               float64
Weather_Condition                object
Amenity                            bool
Bump                               bool
Crossing                           bool
Give_Way                           bool
Junction                           bool
No_Exit                            bool
Railway                            bool
Roundabout                         bool
Station                            bool
Stop                               bool
Traffic_Calming                    bool
Traffic_Signal                     bool
Turning_Loop                       bool
Sunrise_Sunset                   object
Civil_Twilight                   object
Nautical_Twilight                object
Astronomical_Twilight            object
Start_Time_caste         datetime64[ns]
dtype: object

In [7]:
align_census = accidents_df.loc[(accidents_df["Start_Time_caste"] >= pd.to_datetime('2016-01-01')) & (accidents_df["Start_Time_caste"] < pd.to_datetime('2020-01-01'))]
align_census = align_census.sort_values(by=['Start_Time_caste'])
align_census

,ID,Source,TMC,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,...,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight,Start_Time_caste
2716477,A-2716600,Bing,NaN,3,2016-02-08 00:37:08,2016-02-08 06:37:08,40.108910,-83.092860,40.11206,-83.03187,...,False,False,False,False,False,Night,Night,Night,Night,2016-02-08 00:37:08
0,A-1,MapQuest,201.0,3,2016-02-08 05:46:00,2016-02-08 11:00:00,39.865147,-84.058723,NaN,NaN,...,False,False,False,False,False,Night,Night,Night,Night,2016-02-08 05:46:00
2716478,A-2716601,Bing,NaN,2,2016-02-08 05:56:20,2016-02-08 11:56:20,39.865420,-84.062800,39.86501,-84.04873,...,False,False,False,False,False,Night,Night,Night,Night,2016-02-08 05:56:20
1,A-2,MapQuest,201.0,2,2016-02-08 06:07:59,2016-02-08 06:37:59,39.928059,-82.831184,NaN,NaN,...,False,False,False,False,False,Night,Night,Night,Day,2016-02-08 06:07:59
2716480,A-2716603,Bing,NaN,2,2016-02-08 06:15:39,2016-02-08 12:15:39,39.101480,-84.523410,39.09841,-84.52241,...,False,False,False,False,False,Night,Night,Night,Day,2016-02-08 06:15:39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
978772,A-978866,MapQuest,201.0,2,2019-12-31 23:56:42,2020-01-01 01:46:10,35.317268,-120.621109,NaN,NaN,...,False,False,False,False,False,Night,Night,Night,Night,2019-12-31 23:56:42
3736038,A-3742899,Bing,NaN,3,2019-12-31 23:58:17,2020-01-01 00:27:03,41.875610,-87.641550,41.87571,-87.64355,...,False,False,False,False,False,Night,Night,Night,Night,2019-12-31 23:58:17
3736037,A-3742898,Bing,NaN,3,2019-12-31 23:58:17,2020-01-01 00:27:03,41.872480,-87.645740,41.87036,-87.64508,...,False,False,False,False,False,Night,Night,Night,Night,2019-12-31 23:58:17
3736040,A-3742901,Bing,NaN,3,2019-12-31 23:58:17,2020-01-01 00:27:03,41.874100,-87.645980,41.87248,-87.64574,...,False,False,False,False,False,Night,Night,Night,Night,2019-12-31 23:58:17
3736039,A-3742900,Bing,NaN,3,2019-12-31 23:58:17,2020-01-01 00:27:03,41.901500,-87.920340,41.90963,-87.93019,...,False,False,False,False,False,Night,Night,Night,Night,2019-12-31 23:58:17

In [8]:
# Find Portland accidents
portland = align_census.loc[(align_census["City"] == "Portland") & (align_census["State"] == "OR")]
portland

,ID,Source,TMC,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,...,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight,Start_Time_caste
2855567,A-2855690,Bing,NaN,4,2016-06-23 09:46:02,2016-06-23 15:46:02,45.491499,-122.677601,45.492590,-122.676930,...,False,False,False,False,False,Day,Day,Day,Day,2016-06-23 09:46:02
2855570,A-2855693,Bing,NaN,4,2016-06-23 10:19:32,2016-06-23 16:19:32,45.491049,-122.678191,45.494730,-122.677230,...,False,False,False,True,False,Day,Day,Day,Day,2016-06-23 10:19:32
2855571,A-2855694,Bing,NaN,4,2016-06-23 10:19:32,2016-06-23 16:19:32,45.494414,-122.677311,45.491049,-122.678191,...,False,True,False,False,False,Day,Day,Day,Day,2016-06-23 10:19:32
2855610,A-2855733,Bing,NaN,2,2016-06-23 14:33:20,2016-06-23 20:33:20,45.527111,-122.665370,45.527108,-122.665370,...,False,False,False,False,False,Day,Day,Day,Day,2016-06-23 14:33:20
2855903,A-2856026,Bing,NaN,4,2016-06-24 22:53:20,2016-06-25 04:53:20,45.444070,-122.737430,45.441552,-122.748126,...,False,False,False,False,False,Night,Night,Night,Day,2016-06-24 22:53:20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3752694,A-3759555,Bing,NaN,2,2019-12-31 18:37:27,2019-12-31 22:37:27,45.415950,-122.744180,45.415950,-122.744180,...,False,False,False,False,False,Night,Night,Night,Night,2019-12-31 18:37:27
990120,A-990214,MapQuest,201.0,2,2019-12-31 18:39:44,2019-12-31 19:09:20,45.504581,-122.486504,NaN,NaN,...,False,False,False,False,False,Night,Night,Night,Night,2019-12-31 18:39:44
3752700,A-3759561,Bing,NaN,2,2019-12-31 19:04:26,2019-12-31 23:04:26,45.443620,-122.777440,45.443620,-122.777440,...,False,False,False,False,False,Night,Night,Night,Night,2019-12-31 19:04:26
990121,A-990215,MapQuest,201.0,2,2019-12-31 20:35:48,2019-12-31 21:25:13,45.535069,-122.660629,NaN,NaN,...,False,False,False,True,False,Night,Night,Night,Night,2019-12-31 20:35:48
3752711,A-3759572,Bing,NaN,2,2019-12-31 20:52:39,2020-01-01 00:52:39,45.556040,-122.678710,45.556040,-122.678710,...,False,False,False,False,False,Night,Night,Night,Night,2019-12-31 20:52:39

In [9]:
# Remove unwanted columns
portland = portland[["Source", "Severity", "Start_Time", "Start_Time_caste", "Start_Lat", "Start_Lng", "City", "State", "Zipcode", "Description", "Temperature(F)", "Weather_Condition", "Visibility(mi)", "Wind_Speed(mph)"]]
portland

,Source,Severity,Start_Time,Start_Time_caste,Start_Lat,Start_Lng,City,State,Zipcode,Description,Temperature(F),Weather_Condition,Visibility(mi),Wind_Speed(mph)
2855567,Bing,4,2016-06-23 09:46:02,2016-06-23 09:46:02,45.491499,-122.677601,Portland,OR,97239-4003,Closed at Bancroft St - Road closed due to acc...,57.9,Light Rain,10.0,10.4
2855570,Bing,4,2016-06-23 10:19:32,2016-06-23 10:19:32,45.491049,-122.678191,Portland,OR,97239-4004,Closed at Water Ave - Road closed due to accid...,57.9,Light Rain,10.0,10.4
2855571,Bing,4,2016-06-23 10:19:32,2016-06-23 10:19:32,45.494414,-122.677311,Portland,OR,97239,Closed at Hamilton St - Road closed due to acc...,57.9,Light Rain,10.0,10.4
2855610,Bing,2,2016-06-23 14:33:20,2016-06-23 14:33:20,45.527111,-122.665370,Portland,OR,97232,At I-84/US-30/Exit 301 - Accident.,66.0,Mostly Cloudy,10.0,10.4
2855903,Bing,4,2016-06-24 22:53:20,2016-06-24 22:53:20,45.444070,-122.737430,Portland,OR,97219-8632,Closed between I-5 (South) and 68th Pkwy - Roa...,60.1,Partly Cloudy,10.0,6.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3752694,Bing,2,2019-12-31 18:37:27,2019-12-31 18:37:27,45.415950,-122.744180,Portland,OR,97223,At Carman Dr/Exit 291 - Accident.,49.0,Cloudy,10.0,18.0
990120,MapQuest,2,2019-12-31 18:39:44,2019-12-31 18:39:44,45.504581,-122.486504,Portland,OR,97236-1241,Accident on 171st Ave at Division St.,51.0,Light Rain,10.0,17.0
3752700,Bing,2,2019-12-31 19:04:26,2019-12-31 19:04:26,45.443620,-122.777440,Portland,OR,97223,At Greenburg Rd/Exit 5 - Accident.,49.0,Cloudy,10.0,18.0
990121,MapQuest,2,2019-12-31 20:35:48,2019-12-31 20:35:48,45.535069,-122.660629,Portland,OR,97232-1153,Accident on OR-99E Grand Ave at Broadway.,50.0,Light Rain,10.0,13.0
3752711,Bing,2,2019-12-31 20:52:39,2019-12-31 20:52:39,45.556040,-122.678710,Portland,OR,97217,At Killingsworth St/Exit 303 - Accident.,50.0,Light Rain,7.0,6.0

In [10]:
# Drop rows with nulls in any required fields
portland_na = portland.dropna()
portland_na

,Source,Severity,Start_Time,Start_Time_caste,Start_Lat,Start_Lng,City,State,Zipcode,Description,Temperature(F),Weather_Condition,Visibility(mi),Wind_Speed(mph)
2855567,Bing,4,2016-06-23 09:46:02,2016-06-23 09:46:02,45.491499,-122.677601,Portland,OR,97239-4003,Closed at Bancroft St - Road closed due to acc...,57.9,Light Rain,10.0,10.4
2855570,Bing,4,2016-06-23 10:19:32,2016-06-23 10:19:32,45.491049,-122.678191,Portland,OR,97239-4004,Closed at Water Ave - Road closed due to accid...,57.9,Light Rain,10.0,10.4
2855571,Bing,4,2016-06-23 10:19:32,2016-06-23 10:19:32,45.494414,-122.677311,Portland,OR,97239,Closed at Hamilton St - Road closed due to acc...,57.9,Light Rain,10.0,10.4
2855610,Bing,2,2016-06-23 14:33:20,2016-06-23 14:33:20,45.527111,-122.665370,Portland,OR,97232,At I-84/US-30/Exit 301 - Accident.,66.0,Mostly Cloudy,10.0,10.4
2855903,Bing,4,2016-06-24 22:53:20,2016-06-24 22:53:20,45.444070,-122.737430,Portland,OR,97219-8632,Closed between I-5 (South) and 68th Pkwy - Roa...,60.1,Partly Cloudy,10.0,6.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3752694,Bing,2,2019-12-31 18:37:27,2019-12-31 18:37:27,45.415950,-122.744180,Portland,OR,97223,At Carman Dr/Exit 291 - Accident.,49.0,Cloudy,10.0,18.0
990120,MapQuest,2,2019-12-31 18:39:44,2019-12-31 18:39:44,45.504581,-122.486504,Portland,OR,97236-1241,Accident on 171st Ave at Division St.,51.0,Light Rain,10.0,17.0
3752700,Bing,2,2019-12-31 19:04:26,2019-12-31 19:04:26,45.443620,-122.777440,Portland,OR,97223,At Greenburg Rd/Exit 5 - Accident.,49.0,Cloudy,10.0,18.0
990121,MapQuest,2,2019-12-31 20:35:48,2019-12-31 20:35:48,45.535069,-122.660629,Portland,OR,97232-1153,Accident on OR-99E Grand Ave at Broadway.,50.0,Light Rain,10.0,13.0
3752711,Bing,2,2019-12-31 20:52:39,2019-12-31 20:52:39,45.556040,-122.678710,Portland,OR,97217,At Killingsworth St/Exit 303 - Accident.,50.0,Light Rain,7.0,6.0

In [11]:
# Shrink Zipcode to 5 digits if longer
portland_na['Zipcode'] = portland_na['Zipcode'].str[:5]    
portland_na

C:\Users\mrpar\.conda\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Source,Severity,Start_Time,Start_Time_caste,Start_Lat,Start_Lng,City,State,Zipcode,Description,Temperature(F),Weather_Condition,Visibility(mi),Wind_Speed(mph)
2855567,Bing,4,2016-06-23 09:46:02,2016-06-23 09:46:02,45.491499,-122.677601,Portland,OR,97239,Closed at Bancroft St - Road closed due to acc...,57.9,Light Rain,10.0,10.4
2855570,Bing,4,2016-06-23 10:19:32,2016-06-23 10:19:32,45.491049,-122.678191,Portland,OR,97239,Closed at Water Ave - Road closed due to accid...,57.9,Light Rain,10.0,10.4
2855571,Bing,4,2016-06-23 10:19:32,2016-06-23 10:19:32,45.494414,-122.677311,Portland,OR,97239,Closed at Hamilton St - Road closed due to acc...,57.9,Light Rain,10.0,10.4
2855610,Bing,2,2016-06-23 14:33:20,2016-06-23 14:33:20,45.527111,-122.665370,Portland,OR,97232,At I-84/US-30/Exit 301 - Accident.,66.0,Mostly Cloudy,10.0,10.4
2855903,Bing,4,2016-06-24 22:53:20,2016-06-24 22:53:20,45.444070,-122.737430,Portland,OR,97219,Closed between I-5 (South) and 68th Pkwy - Roa...,60.1,Partly Cloudy,10.0,6.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3752694,Bing,2,2019-12-31 18:37:27,2019-12-31 18:37:27,45.415950,-122.744180,Portland,OR,97223,At Carman Dr/Exit 291 - Accident.,49.0,Cloudy,10.0,18.0
990120,MapQuest,2,2019-12-31 18:39:44,2019-12-31 18:39:44,45.504581,-122.486504,Portland,OR,97236,Accident on 171st Ave at Division St.,51.0,Light Rain,10.0,17.0
3752700,Bing,2,2019-12-31 19:04:26,2019-12-31 19:04:26,45.443620,-122.777440,Portland,OR,97223,At Greenburg Rd/Exit 5 - Accident.,49.0,Cloudy,10.0,18.0
990121,MapQuest,2,2019-12-31 20:35:48,2019-12-31 20:35:48,45.535069,-122.660629,Portland,OR,97232,Accident on OR-99E Grand Ave at Broadway.,50.0,Light Rain,10.0,13.0
3752711,Bing,2,2019-12-31 20:52:39,2019-12-31 20:52:39,45.556040,-122.678710,Portland,OR,97217,At Killingsworth St/Exit 303 - Accident.,50.0,Light Rain,7.0,6.0

In [12]:
# Rename columns to simplify access in Mongo
portland_na.rename(columns={
    'Temperature(F)': "Temperature",
    'Visibility(mi)': "Visibility",
    'Wind_Speed(mph)': "Wind_Speed"
}, inplace=True)
portland_na

C:\Users\mrpar\.conda\envs\PythonData\lib\site-packages\pandas\core\frame.py:4133: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

,Source,Severity,Start_Time,Start_Time_caste,Start_Lat,Start_Lng,City,State,Zipcode,Description,Temperature,Weather_Condition,Visibility,Wind_Speed
2855567,Bing,4,2016-06-23 09:46:02,2016-06-23 09:46:02,45.491499,-122.677601,Portland,OR,97239,Closed at Bancroft St - Road closed due to acc...,57.9,Light Rain,10.0,10.4
2855570,Bing,4,2016-06-23 10:19:32,2016-06-23 10:19:32,45.491049,-122.678191,Portland,OR,97239,Closed at Water Ave - Road closed due to accid...,57.9,Light Rain,10.0,10.4
2855571,Bing,4,2016-06-23 10:19:32,2016-06-23 10:19:32,45.494414,-122.677311,Portland,OR,97239,Closed at Hamilton St - Road closed due to acc...,57.9,Light Rain,10.0,10.4
2855610,Bing,2,2016-06-23 14:33:20,2016-06-23 14:33:20,45.527111,-122.665370,Portland,OR,97232,At I-84/US-30/Exit 301 - Accident.,66.0,Mostly Cloudy,10.0,10.4
2855903,Bing,4,2016-06-24 22:53:20,2016-06-24 22:53:20,45.444070,-122.737430,Portland,OR,97219,Closed between I-5 (South) and 68th Pkwy - Roa...,60.1,Partly Cloudy,10.0,6.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3752694,Bing,2,2019-12-31 18:37:27,2019-12-31 18:37:27,45.415950,-122.744180,Portland,OR,97223,At Carman Dr/Exit 291 - Accident.,49.0,Cloudy,10.0,18.0
990120,MapQuest,2,2019-12-31 18:39:44,2019-12-31 18:39:44,45.504581,-122.486504,Portland,OR,97236,Accident on 171st Ave at Division St.,51.0,Light Rain,10.0,17.0
3752700,Bing,2,2019-12-31 19:04:26,2019-12-31 19:04:26,45.443620,-122.777440,Portland,OR,97223,At Greenburg Rd/Exit 5 - Accident.,49.0,Cloudy,10.0,18.0
990121,MapQuest,2,2019-12-31 20:35:48,2019-12-31 20:35:48,45.535069,-122.660629,Portland,OR,97232,Accident on OR-99E Grand Ave at Broadway.,50.0,Light Rain,10.0,13.0
3752711,Bing,2,2019-12-31 20:52:39,2019-12-31 20:52:39,45.556040,-122.678710,Portland,OR,97217,At Killingsworth St/Exit 303 - Accident.,50.0,Light Rain,7.0,6.0

In [10]:
# Don't need to run but was part of Marker Cluster map setting
portland_na.to_json("data\portland_cleaned.json", orient="records")

In [13]:
# Mongo DB dependencies
import pymongo

# The default port used by MongoDB is 27017
conn = 'mongodb://localhost:27017'
client = pymongo.MongoClient(conn)

# Define the accident database in Mongo
db = client.accidents_db

# Define accidents Collection
accident = db.accidents

In [14]:
# Iterature through final Portland dataframe and create Mongo accident collection
for index, row in portland_na.iterrows():
    accident_data={    
        "Source" : row['Source'],
        "Severity" : row['Severity'],
        "Start_Time" : row['Start_Time'],
        "Start_Lat" : row['Start_Lat'],
        "Start_Lng" : row['Start_Lng'],
        "City" : row['City'],
        "Zipcode" : row['Zipcode'],
        "State" : row['State'],
        "Description" : row['Description'],
        "Temperature" : row['Temperature'],
        "Weather_Condition" : row['Weather_Condition'],
        "Visibility" : row['Visibility'],
        "Wind_Speed" : row['Wind_Speed'],
    }
    
    #import into MongoDB         
    accident.insert_one(accident_data)

In [15]:
# Retrieve census data from JSON
census_data = pd.read_json("census_data\cleaned_census\census_merged.json")
census_data.dtypes

Zipcode                int64
Population             int64
Median Age           float64
Household Income       int64
Per Capita Income      int64
Poverty Count          int64
Poverty Rate         float64
Year                   int64
dtype: object

In [16]:
db = client.accidents_db
census = db.census

for index, row in census_data.iterrows():
    zipcode_data={    
        "Zipcode" : row['Zipcode'],
        "Population" : row['Population'],
        "MedianAge" : row['Median Age'],
        "HouseholdIncome" : row['Household Income'],
        "PerCapitaIncome" : row['Per Capita Income'],
        "PovertyCount" : row['Poverty Count'],
        "PovertyRate" : row['Poverty Rate'],
        "Year" : row['Year'],
    }
    
    #import into MongoDB         
    census.insert_one(zipcode_data)